### ISSUE TITLE
Install failed

### ISSUE THREAD

**Issue by yukun-kooboo** [storybooks/babel-plugin-paths#2]
I run 'yarn add babel-plugin-module-paths' command, and then I got this feedback below:

PS C:\> yarn add babel-plugin-module-paths
yarn add v1.5.1
[1/5] Validating package.json...
[2/5] Resolving packages...
error An unexpected error occurred: "https://registry.npmjs.org/babel-plugin-module-paths: Not found".
info If you think this is a bug, please open a bug report with the information provided in "C:\\GoBear\\GoBear_DesignPantry\\yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.

Has this module been removed from npm?

**Comment by Qix-** [comment]
There's no way this got unpublished, `npm` doesn't allow for it to happen. However, I'm seeing this too.

**Comment by Isakdl** [comment]
Have the same issue

**Comment by igor-dv** [comment]
The package is called `paths.macro`, docs are wrong 🤷‍♂️

**Comment by dzienisz** [comment]
`yarn add paths.macro`
